// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zbhczmxiajmpnynatdqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiaGN6bXhpYWptcG55bmF0ZHFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMjY0OTUsImV4cCI6MjA3NDkwMjQ5NX0.hpTDH3yCL2X5tOdtvfDai1jCYOjbjktGGDfW2mONFm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);